cmake_minimum_required(VERSION 3.25)
# Run with: cmake -DBUILD_ROOT=<empty directory> -P tests/install_package.cmake
if(NOT DEFINED BUILD_ROOT OR EXISTS "${BUILD_ROOT}")
    message(FATAL_ERROR "Supply a new BUILD_ROOT for the isolated install test")
endif()
get_filename_component(SDK_SOURCE "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(BUILD_ROOT "${BUILD_ROOT}" ABSOLUTE)
get_filename_component(cmake_dir "${CMAKE_COMMAND}" DIRECTORY)
find_program(ctest NAMES ctest HINTS "${cmake_dir}" REQUIRED)
function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Command failed: ${ARGV}")
    endif()
endfunction()
foreach(bundle IN ITEMS ON OFF)
    set(root "${BUILD_ROOT}/${bundle}")
    run("${CMAKE_COMMAND}" -S "${SDK_SOURCE}" -B "${root}/sdk-build" -A x64
        -DBUILD_TESTING=OFF "-DSFSEMCP_BUNDLE_SIGNING_HEADERS=${bundle}"
        "-DCMAKE_INSTALL_PREFIX=${root}/installed")
    run("${CMAKE_COMMAND}" --install "${root}/sdk-build" --config Release)
    file(RENAME "${root}/installed" "${root}/relocated")
    if(bundle)
        set(signing_include "${root}/relocated/include")
        if(EXISTS "${signing_include}/CLibUtilsQTR/utils.hpp")
            message(FATAL_ERROR "Unrelated QTR headers were installed")
        endif()
        set(dependency_args)
    else()
        if(EXISTS "${root}/relocated/include/CLibUtilsQTR")
            message(FATAL_ERROR "External-dependency mode bundled QTR headers")
        endif()
        set(signing_include "${root}/qtr/include")
        file(COPY "${SDK_SOURCE}/lib/clib-utils-qtr/include/CLibUtilsQTR"
            DESTINATION "${signing_include}")
        set(dependency_args "-DCMAKE_PREFIX_PATH=${root}/qtr")
    endif()
    run("${CMAKE_COMMAND}" -S "${SDK_SOURCE}/tests/install-consumer"
        -B "${root}/consumer-build" -A x64
        "-DSFSE-MCP_DIR=${root}/relocated/lib/cmake/SFSE-MCP"
        "-DEXPECTED_SIGNING_INCLUDE_DIR=${signing_include}" ${dependency_args})
    run("${CMAKE_COMMAND}" --build "${root}/consumer-build" --config Release)
    run("${ctest}" --test-dir "${root}/consumer-build" -C Release --output-on-failure)
endforeach()
