param([string] $OutputDirectory)

$ErrorActionPreference = 'Stop'
$source = Split-Path -Parent $PSScriptRoot
$include = [IO.Path]::GetFullPath((Join-Path $source 'include\SFSEMCP'))
$qtr = [IO.Path]::GetFullPath((Join-Path $source 'lib\clib-utils-qtr'))
$qtrInclude = Join-Path $qtr 'include'
$project = [IO.File]::ReadAllText((Join-Path $source 'CMakeLists.txt'))
if ($project -notmatch '(?m)^\s*VERSION\s+(\d+\.\d+\.\d+)\s*$') { throw 'SDK version not found.' }
$version = $Matches[1]
if (-not $OutputDirectory) { $OutputDirectory = Join-Path $source 'build\packages' }
$output = [IO.Path]::GetFullPath($OutputDirectory)

$headers = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
$text = [Text.StringBuilder]::new()
[void] $text.Append("#pragma once`n`n// SFSE-MCP $version - generated by scripts/Package-Sdk.ps1.`n/*`n")
foreach ($notice in @('LICENSE', 'THIRD_PARTY_NOTICES')) {
    [void] $text.Append([IO.File]::ReadAllText((Join-Path $source $notice)).Replace("`r`n", "`n"))
    [void] $text.Append("`n")
}
[void] $text.Append("*/`n")
[void] $text.Append("/* CLibUtilsQTR signing module`n")
[void] $text.Append([IO.File]::ReadAllText((Join-Path $qtr 'LICENSE')).Replace("`r`n", "`n"))
[void] $text.Append("`n*/`n")

function Expand-Header([string] $Path) {
    $fullPath = [IO.Path]::GetFullPath($Path)
    if (-not $fullPath.StartsWith($include + '\', [StringComparison]::OrdinalIgnoreCase) -and
        -not $fullPath.StartsWith($qtrInclude + '\CLibUtilsQTR\Signing\', [StringComparison]::OrdinalIgnoreCase) -and
        $fullPath -ine (Join-Path $qtrInclude 'CLibUtilsQTR\Signing.hpp')) {
        throw "Header leaves the SDK or QTR signing include directory: $Path"
    }
    if (-not $headers.Add($fullPath)) { return }
    foreach ($line in [IO.File]::ReadAllLines($fullPath)) {
        if ($line -match '^\s*#\s*pragma\s+once\s*$') { continue }
        if ($line -match '^\s*#\s*include\s+"([^"]+)"\s*$') {
            Expand-Header (Join-Path (Split-Path -Parent $fullPath) $Matches[1])
        } elseif ($line -match '^\s*#\s*include\s+<(CLibUtilsQTR/Signing(?:/[^>]+|\.hpp))>\s*$') {
            Expand-Header (Join-Path $qtrInclude $Matches[1])
        } else {
            # Preserve system includes and the conditional custom signing-key include.
            [void] $text.Append($line).Append("`n")
        }
    }
}

Expand-Header (Join-Path $include 'SFSEMenuFramework.hpp')
$header = $text.ToString()
if ($header -match '(?m)^\s*#\s*include\s*("|<SFSEMCP/|<CLibUtilsQTR/)') {
    throw 'Generated header still depends on another SDK header.'
}

New-Item -ItemType Directory -Path $output -Force | Out-Null
$archivePath = Join-Path $output "SFSE-MCP-$version-SDK.zip"
$utf8 = [Text.UTF8Encoding]::new($false)
$files = [ordered]@{
    'SFSEMCP/SFSEMenuFramework.hpp' = $utf8.GetBytes($header)
    'LICENSE' = [IO.File]::ReadAllBytes((Join-Path $source 'LICENSE'))
    'THIRD_PARTY_NOTICES' = [IO.File]::ReadAllBytes((Join-Path $source 'THIRD_PARTY_NOTICES'))
    'README.txt' = $utf8.GetBytes(@"
SFSE-MCP $version - single-header SDK

Copy SFSEMCP into your C++ project's include directory and use:
#include <SFSEMCP/SFSEMenuFramework.hpp>

Requires C++23, Windows x64, and SFSE Menu Framework at runtime.
No vcpkg, signing tools, or private key is needed by client mod authors.
Keep the embedded license notices when copying the header.
Do not mix this download with the multi-file SDK in the same project.
"@)
}
Add-Type -AssemblyName System.IO.Compression
$stream = [IO.File]::Open($archivePath, [IO.FileMode]::Create, [IO.FileAccess]::Write)
try {
    $zip = [IO.Compression.ZipArchive]::new($stream, [IO.Compression.ZipArchiveMode]::Create)
    try {
        foreach ($file in $files.GetEnumerator()) {
            $entry = $zip.CreateEntry($file.Key, [IO.Compression.CompressionLevel]::Optimal)
            $entry.LastWriteTime = [DateTimeOffset]::new(2000, 1, 1, 0, 0, 0, [TimeSpan]::Zero)
            $entryStream = $entry.Open()
            try { $entryStream.Write($file.Value, 0, $file.Value.Length) } finally { $entryStream.Dispose() }
        }
    } finally { $zip.Dispose() }
} finally { $stream.Dispose() }
Write-Output $archivePath
